#!/bin/bash
#set -eux
# a script that checks if connection is down for 5 minutes
# then waits till connection comes back again
# exits tmate session 
# creates a new tmate session and send session id using a telegram bot
#!/bin/bash
set -x
TOKEN=""
CHAT_ID=""
URL="https://api.telegram.org/bot$TOKEN/sendMessage"


export PATH=$PATH:$PWD
while true ; do
    killall tmate
    tmate -S /tmp/tmate.sock new-session -d
    tmate -S /tmp/tmate.sock wait tmate-ready
    export MESSAGE=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' 2>&1)
    curl -s -X POST $URL -d chat_id=${CHAT_ID} -d text="${MESSAGE}"  2> /dev/null
    while ls /tmp/tmate.sock ; do
        new_message=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' 2>&1)
        if [[ "${new_message}" != "${MESSAGE}" ]] ; then
            export MESSAGE="${new_message}"
            curl -s -X POST $URL -d chat_id=${CHAT_ID} -d text="${MESSAGE}"  2> /dev/null
        fi
  sleep 10
    done
done
